background_opacity 0.85

font_family Terminus (TTF) 
bold_font auto 
italic_font auto 
bold_italic_font auto 
font_size 10

background #0B0F0E
foreground #C7F0D8
cursor     #00FF9C

selection_background #1F2A28
selection_foreground #E8FFF3

color0  #0B0F0E
color1  #FF6B6B
color2  #2EFFA3
color3  #FFD166
color4  #6BCBFF
color5  #C77DFF
color6  #4DFFFF
color7  #E6FFF2

color8  #2A3A36
color15 #FFFFFF
